### ISSUE TITLE
Question about saving

### ISSUE THREAD

**Issue by davidcortesortuno** [MathieuMoalic/amumax#100]
Hi, I'm trying to understand the new `zarr` format which looks very handy for processing the data.
In my simulation I want to save a single magnetic state after relaxation so I use a code like this in my script:

```
DN := 20.0
simname := sprintf("m_dx%02.0fA", DN)
SaveAs(m, simname)
```

which produces the `m_dx20A/` directory. This folder contains a `0.0.0.0.0` compressed file. I guess these are the dimensions of time, nz, ny, nx and the 3 m-components? I opened the directory with `zarr` and I could retrieve the data using the indexing `data[0, 0, 0, :]`. 
My other question is if it's possible to get the mesh coordinates in this file format, so it's easier to process the data.

Is the `SaveAs` function ok to use? Or is it better to use another one, like `autosave` ?

By the way, I want to suggest you open the Discussions feature in this repository, so it's easier to ask questions rather than raising issues 😊
Cheers

**Comment by davidcortesortuno** [comment]
Maybe it's easier if I attach my script [one_dim_inter.txt](https://github.com/user-attachments/files/18100866/one_dim_inter.txt) . This is a 1D chain with exchange and dmi, where I change the number of cells on every iteration (to improve resolution). When I save the files I get the attributes for the coordinates in the main folder in the `.zattrs` file, however for the sub-arrays, the `.zattrs` file only contains the `t` (time) key. I hoped this should contain the modified `nx` attribute since my mesh changed.

**Comment by MathieuMoalic** [comment]
Hi there,

"This folder contains a 0.0.0.0.0 compressed file. I guess these are the dimensions of time, nz, ny, nx and the 3 m-components? ": The numbers correspond more or less to chunks in the dataset, you don't really need to know them to access the data.

"My other question is if it's possible to get the mesh coordinates in this file format": there are a couple options, you can call the `.shape()` function on the numpy array or zarr dataset i.e. `job.m.shape()` or you can read one of the saved zarr attributes (you can find them in job.zarr/.zattrs )for example `job.Nx` is the grid size along x.

"Is the SaveAs function ok to use? Or is it better to use another one, like autosave ?": they have different uses, SaveAs will save once with a custom name, AutoSave will save every interval with the default name, for example when you use Run(). 

I will enable the discussions, it is a good idea!
