### ISSUE TITLE
New feature and bugs:  version selection and interface problems in latest version

### ISSUE THREAD

**Issue by kkingstoun** [MathieuMoalic/amumax#28]
# New feature request: Version selection
I propose to add a feature that allows users to select a specific tag/version of amumax during installation. This would allow users to install the appropriate version for their needs or environment.

# Bug report: Interface problems in latest version
In the latest release (dated 28.08.2024) there are a couple of critical issues:

Console not working: The console functionality does not seem to work.

View mode switching: It's currently impossible to switch from 3D to 2D view.

**Comment by MathieuMoalic** [comment]
Fixed
