### ISSUE TITLE
Building amumax

### ISSUE THREAD

**Issue by davidcortesortuno** [MathieuMoalic/amumax#29]
Hi, I'm trying to compile amumax using cuda 12.6, so if I follow part of the instructions:

```
git clone https://github.com/MathieuMoalic/amumax
cd amumax
bash cuda/build_cuda.sh
```

This compiles the cuda modules correctly if I set the `ccbin` flag to `gcc-13` in my system. 
Then I do `go install` and I got

```
 go install
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/minio/selfupdate v0.6.0
go: downloading github.com/labstack/echo/v4 v4.12.0
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading golang.org/x/term v0.22.0
go: downloading github.com/vmihailenco/msgpack/v5 v5.4.1
go: downloading github.com/DataDog/zstd v1.5.5
go: downloading aead.dev/minisign v0.3.0
go: downloading github.com/vmihailenco/tagparser/v2 v2.0.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/net v0.27.0
go: downloading golang.org/x/crypto v0.25.0
go: downloading github.com/labstack/gommon v0.4.2
go: downloading github.com/valyala/fasttemplate v1.2.2
go: downloading golang.org/x/time v0.5.0
go: downloading github.com/golang-jwt/jwt v3.2.2+incompatible
go: downloading golang.org/x/text v0.16.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
api/static.go:11:12: pattern static/*: no matching files found
```

So I changed line 11 in the last file to `// go:embed static/*` (extra space after `//`) and it continues ok. But finally I get an error

```
# github.com/MathieuMoalic/amumax/cuda/curand
cuda/curand/generator.go:3:10: fatal error: curand.h: No such file or directory
    3 | //#include <curand.h>
      |          ^~~~~~~~~~
compilation terminated.
# github.com/MathieuMoalic/amumax/cuda/cu
cuda/cu/context.go:5:11: fatal error: cuda.h: No such file or directory
    5 | // #include <cuda.h>
      |           ^~~~~~~~
compilation terminated.
```

Is this the right way to build the amumax executable?

Cheers

**Comment by MathieuMoalic** [comment]
Hi, the build steps are out of date indeed.  I will update it on Wednesday. In the mean time, would the pre-compiled binaries work for you?

**Comment by davidcortesortuno** [comment]
Thanks. I tried the binaries but it cannot find the `curan` or `fft` libraries. Is there an env variable I should set to the binary finds the libraries?

**Comment by MathieuMoalic** [comment]
You need to copy libcurand.so and libcufft.so in the same folder as the amumax binary

**Comment by MathieuMoalic** [comment]
You need to copy libcurand.so and libcufft.so in the same folder as the amumax binary. Did you try the install script? Does it give you an error?

**Comment by davidcortesortuno** [comment]
Ah ok, I was asking about compiling myself as the latest cuda has only `libcufft` version 11. I was also not sure if it might work as there are multiple files related to cuda fft:

```
/usr/local/cuda-12.6/lib64/libcufft.so@            /usr/local/cuda-12.6/lib64/libcufft_static.a             /usr/local/cuda-12.6/lib64/libcufftw.so.11@
/usr/local/cuda-12.6/lib64/libcufft.so.11@         /usr/local/cuda-12.6/lib64/libcufft_static_nocallback.a  /usr/local/cuda-12.6/lib64/libcufftw.so.11.2.6.59*
/usr/local/cuda-12.6/lib64/libcufft.so.11.2.6.59*  /usr/local/cuda-12.6/lib64/libcufftw.so@                 /usr/local/cuda-12.6/lib64/libcufftw_static.a
```

I guess, to run the binary, I need to download an older cuda version

**Comment by MathieuMoalic** [comment]
I compiled it with an older cuda version for compatibility reasons. Amumax does not need any of the new features from libcufft.11. libcufft.so@  and libcufft.so.11@  are synlinks to libcufft.so.11.2.6.59, the actually library. We don't use libcufftw. 

If you don't want to run this install script `sh -c "$(curl -fsSL https://raw.githubusercontent.com/MathieuMoalic/amumax/main/install.sh)"` which will automatically download the amumax binary and the proper cuda libraries for you then you will have to compile it yourself.

The easy way is to use docker ( or podman ) to build the amumax image and run it to build:
```bash
podman build -t matmoa/amumax:build .
podman run --rm -v $PWD:/src matmoa/amumax:build sh cuda/build_cuda.sh
podman run --rm \
-v .:/app \
-w /app/frontend \
docker.io/oven/bun:1.1.26-debian bash -c 'bun install && bun run 
podman run --rm -v $PWD:/src matmoa/amumax:build
rm -r frontend/dist
```
If you have nix: `nix run .`

It is still not clear to me if you want to just run the binary or make changes to the code and compile it yourself.

**Comment by davidcortesortuno** [comment]
Hi, thanks for the instructions. I ran the install script and could run `amumax`, it works fine.

I was also trying to build it myself, in case I wanted to add something to the code. But I will wait for the updates :)

**Comment by MathieuMoalic** [comment]
I updated the build instructions in  #40. Let me know if you have any issues.
