### ISSUE TITLE
Add Preview Resolution Control via Script Variables (pNx / pDx) and GUI Interface

### ISSUE THREAD

**Issue by kkingstoun** [MathieuMoalic/amumax#53]
![image](https://github.com/user-attachments/assets/41075d79-a0a5-4eae-b913-e3b80bd7cae8)

Here’s a draft for your GitHub issue:

Title: Feature Request: Add Preview Resolution Control via Script Variables (pNx / pDx) and GUI Interface

I would like to propose adding a new feature to amumax that allows users to set the preview resolution in simulation scripts. This can be achieved by introducing new variables: pNx (preview Nx) and pDx (preview Dx). These variables would allow users to define the resolution of the preview directly in the script, providing more control over the visualization of simulations.

Additionally, I suggest updating the graphical interface to support these options (see attached image). Users should be able to easily adjust the preview resolution through slider or input field in the GUI.

**Comment by Kami-prog** [comment]
download
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by MathieuMoalic** [comment]
b12382d9990bb6e8d68f5cc4e7c5ebdd4b817739
