### ISSUE TITLE
New Feature Request: Ability to run postprocessing scripts after simulation completion

### ISSUE THREAD

**Issue by kkingstoun** [MathieuMoalic/amumax#56]
I propose adding functionality to automatically trigger Python scripts for postprocessing directly after a simulation completes in amumax. This would streamline the simulation workflow, allowing users to automatically process data without needing to manually run additional scripts after each simulation.

We can add a new function to the mumax3 scripting API, called runPython(), that allows users to specify a Python script (and optionally, arguments) to be executed automatically once the mumax3 simulation is complete.

```
// Simulation setup
run(100e-9) // Run the simulation for 100ns

// Postprocessing step: Run Python script after simulation
runPython("postprocess.py", ["output_file.ovf"])
```

**Comment by MathieuMoalic** [comment]
`RunShell("blahblah")`
