### ISSUE TITLE
Feature Request: Add index to table

### ISSUE THREAD

**Issue by kkingstoun** [MathieuMoalic/amumax#66]
I would like to suggest adding the ability to display data in table against an "iterator", such as time or other parameters. This would allow for more flexible data visualization in web GUI, especially in cases where an iteration step (e.g., time step, specific parameter scan) is more relevant than absolute time or field values.

**Comment by MathieuMoalic** [comment]
I do not understand

**Comment by MathieuMoalic** [comment]
Added in 9eb3040730711b7d7f4774770ea254a96117c580
