### ISSUE TITLE
Support subpath for amumax --webui-host

### ISSUE THREAD

**Issue by timvgl** [MathieuMoalic/amumax#81]
Hi,
we would like to deploy amumax behind a reverse proxy under the following scheme:
host:port/node/foo/faa/...
Could you add support for this into the frontend so that client side URLs are translateable.
e.g. [		let wsUrl = '/ws';](https://github.com/MathieuMoalic/amumax/blob/850575d5c0a4483704ecdeb37f35206dcb426e81/frontend/src/api/websocket.ts#L23) -> let ws = BASE_URL + '/ws'
Best regards,
Tim Vogel

**Comment by timvgl** [comment]
Hi,
we cannot really solve this with the settings of the reverse proxy.
We would propose to just set it as an enviromental variable.
We have already done something like that with the classical mumax3 version.
https://github.com/mumax/3/commit/2b06b2679ec71ddf8ea986728b21ec1adad4ebf3#diff-513488a90e3796033af837de4279c3a92dd49ae036487a2511e22fd4a06e541e
Thanks for your time and the efforts,
Tim

**Comment by CptCrispyCrunchy** [comment]
Hey,
just adding to @timvgl as we are currently working together on this:

I get the following things to work with our reverse proxy
[x] route to the local container port and service
[x] strip the url prefixes "/node/id/service_name" and access the container under root path "/". We can successfully route to your web application!

Now what we do not get to work easily with our setup:  

Client receives rendered pages / JS code from server with embedded urls starting at the root path. However, I need these urls to go to "/node/id/service_name/path". We can solve this without touching your code by adding response middleware that rewrites urls to the one we want but this solution is harder to get right, especially as you have some urls embedded in your JS code. You would need to write regex matches for all url schemes and places. Feasible, but not ideal.

What would be nice is the ability, like Tim already mentioned, to set a `BASE_URL` via an environment variable. That is possible in your setup as well:

1. Read env variable from server side code (`+layout.server.ts` file)
2. Add a config route that serves a simple JSON to your frontend client.
3. In client side `+layout.ts`, fetch this config JSON and configure the client side part of your web application, e.g. via a store.

This way you can have your server/backend completely in control over the configuration. The backend could even be a golang server and you don't need to config during compile time.

Thank you for your work on this GUI btw, looks great!

Cheers,
Milan

**Comment by MathieuMoalic** [comment]
Thank for the explaination. You seem a lot more knowledgeable than me on this subject. Depending on my free time I might implement it in the next few days or weeks. Of course, I'm always happy to receive PRs as well :)

**Comment by MathieuMoalic** [comment]
I will try injecting a variable in this function:
https://github.com/MathieuMoalic/amumax/blob/a3f612d37823f72b1e26250c165bbc3bb3d44c58/src/api/static.go#L24

**Comment by MathieuMoalic** [comment]
@CptCrispyCrunchy @timvgl I just created a PR #88 , can you test it and report if it is behaving as you would expect. Notice that I changed the cli flag, you can use `--webui-addr=localhost:35367/proxy/worker1` for example

**Comment by timvgl** [comment]
@MathieuMoalic thanks for the work.
As far as I got it, it is not necessary to run another backend server. I think it is really only about adapting the internally used links.
I get some error messages in the inspector and the webinterface is not loading.
Here a picture from the inspector.
![grafik](https://github.com/user-attachments/assets/bfc030e2-0e28-40cd-a9fa-2d1f715b8103)
Thanks again for the efforts

**Comment by CptCrispyCrunchy** [comment]
@MathieuMoalic thanks a lot for the PR! We got it working now :). The last issue seems to have been on our side... we accidentally had a loadbalancer going wild and routing the websocket connection between different simulation containers. Now, also the links embedded in the html work correctly and we can see the liveplots. 

And yes, you don't need an additional backend but I think you got it right anyhow ;). I've just gone over your codebase very quickly before making those suggestions and thought you used sveltekit also as a backend but it seems like you just deploy it as SPA?

**Comment by MathieuMoalic** [comment]
I'm glad it works, I will merge it in the main branch soon and make a new release :)
As for the frontend, I use sveltkit but I use the static adapter (https://github.com/MathieuMoalic/amumax/blob/7f7268ae9e3084a55235edc9648adfdaa6208fa8/frontend/svelte.config.js#L1)
So all SSR is disabled. It makes shipping the frontend very easy thanks to embed.FS https://github.com/MathieuMoalic/amumax/blob/7f7268ae9e3084a55235edc9648adfdaa6208fa8/src/api/static.go#L11
