### ISSUE TITLE
Skip-exist doesn't work with queue

### ISSUE THREAD

**Issue by kkingstoun** [MathieuMoalic/amumax#91]
m --webui-queue-port=12412 --skip-exist 0.0*.mx3 
Error executing squeue: exec: "squeue": executable file not found in $PATH
// Error getting SLURM end time: exec: "squeue": executable file not found in $PATH
// Version:         2024.11.22
// Platform:        linux_amd64
// Go Version:      go1.22.5 (gc)
// CUDA Version:    11.0 (CC=52 PTX)
// GPU Information: NVIDIA H100(95350MB), CUDA Driver 12.6, cc=9.0
  0 0.001.mx3 
  1 0.017.mx3 
  2 0.025.mx3 
  3 0.033.mx3 
  4 0.041.mx3 
  5 0.049.mx3 
  6 0.057.mx3 
  7 0.065.mx3 
  8 0.07300000000000001.mx3 
  9 0.08100000000000002.mx3 
 10 0.08900000000000002.mx3 
 11 0.009000000000000001.mx3 
 12 0.09700000000000003.mx3 
Running 0.001.mx3 on GPU 0

However, folder exists: 

![image](https://github.com/user-attachments/assets/0c7c987c-9a57-4f35-ac4e-a7079af1493e)

**Comment by MathieuMoalic** [comment]
e3148d400e11600ad626dcfe506858e69ad9ecec
